name: build-and-push-image

on:
  workflow_dispatch:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Setup golang
        id: golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19.0

      - name: Run generate
        id: generate
        env:
          GOOS: linux
          GOARCH: amd64
        run: make generate

      - name: Run build
        id: build
        env:
          GOOS: linux
          GOARCH: amd64
        run: make build

      - name: "Container registry login"
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Extract metadata (tags, labels) for Docker"
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.linux.amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}